## Server properties
server:
  port: 8080

## Primary/Target Database Properties
spring:
  datasource:
    url: jdbc:mysql://localhost:3305/customerdb
    username: root
    password: root
  jpa.hibernate.ddl-auto: create-drop
  jpa.show-sql: true

## Source Database Properties
customer:
  datasource:
    host: localhost
    port: 3304
    database: customerdb
    username: root
    password: root

## Logging properties
logging:
  level:
    root: INFO
    io:
      debezium:
        mysql:
          BinlogReader: INFO
    com:
      baeldung:
        libraries:
          debezium: DEBUG

#debezium:
#  properties:
#    database:
#      dbname: delivery
#      port: '3306'
#      server:
#        id: '85744'
#        name: debezium-connector
#      hostname: localhost
#      password: password
#      history:
#        file:
#          filename: /Users/oleksandr.hladun/debezium/dbhistory.dat
#        nodeValue: io.debezium.relational.history.FileDatabaseHistory
#      allowPublicKeyRetrieval: 'true'
#      user: root
#      include:
#        list: delivery
#    offset:
#      flush:
#        interval:
#          ms: '60000'
#      storage:
#        file:
#          filename: /Users/oleksandr.hladun/debezium//offset.dat
#        nodeValue: org.apache.kafka.connect.storage.FileOffsetBackingStore
#    include:
#      schema:
#        changes: 'false'
#    name: my-sql-connector
#    connector:
#      class: io.debezium.connector.mysql.MySqlConnector
#    table:
#      include:
#        list: delivery.outbox
